/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353534",
        "secondary-fixed": "#ffe088",
        "error-container": "#93000a",
        "surface-bright": "#393939",
        "on-primary": "#4d2600",
        "error": "#ffb4ab",
        "on-tertiary-container": "#404021",
        "surface-container-highest": "#353534",
        "inverse-primary": "#904d00",
        "outline-variant": "#564334",
        "tertiary-container": "#adac84",
        "on-tertiary-fixed": "#1d1d03",
        "on-tertiary": "#323214",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#ffb77d",
        "secondary-fixed-dim": "#e9c349",
        "secondary-container": "#af8d11",
        "tertiary-fixed-dim": "#cac99f",
        "on-surface-variant": "#ddc1ae",
        "surface-container-low": "#1c1b1b",
        "primary": "#ffb77d",
        "on-secondary-container": "#342800",
        "primary-fixed-dim": "#ffb77d",
        "secondary": "#e9c349",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#6e3900",
        "on-primary-fixed": "#2f1500",
        "on-secondary": "#3c2f00",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#574500",
        "on-background": "#e5e2e1",
        "on-primary-container": "#623200",
        "primary-fixed": "#ffdcc3",
        "tertiary": "#cac99f",
        "on-error": "#690005",
        "background": "#131313",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#484828",
        "tertiary-fixed": "#e6e5b9",
        "outline": "#a48c7a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#ff8c00",
        "surface": "#131313",
        "on-secondary-fixed": "#241a00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
